# 註:yaml的空值是~或是null

# 讓爬蟲登入用的帳號 建議用分身帳號
Account: vscode
Password: abcd1234

# 要紀錄PTT上線時間的目標帳號 支援多組帳號
Targets:
- account: digforapples
  IsSendWater: true
#- account: vi000246
#  IsSendWater: true
#- account: assai000
#  IsSendWater: true

# 發送水球的目標
WaterTarget: vi000246

# Service要定期執行的間隔 單位:秒
SleepTime: 300

# 程式所在目錄
ProgramePath: D:\Project\PttUserOnlineRecord\PttUserOnlineRecord